<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Python Programming</title>
    <link rel="stylesheet" type="text/css" href="my.css">
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
</head>


<pre>
    <code class="inline_code">
def remove_num(arr, num):
    #your code here!
    return 0
     
#Unit Tests

def asserter(test_case, exp, func, *args):
    try:
        ret = func(*args)
       if ret == exp:
           print("Test Case " + str(test_case) + " SUCCESS!")
       else:
          print("Test Case " + str(test_case) + " FAILED. We expected: " + str(exp) + " but you returned " + str(ret))
    except Exception as e:
        print("Test Case " + str(test_case) + f" had an exception: {type(e).__name__}: {e}")

asserter(1, [1,2,3], remove_num, [0,1,2,3], 0)
asserter(2, [1,2], remove_num, [2], 1)
asserter(3, [1], remove_num, [], 1)
asserter(4, [1,2], remove_num, [1,2], 3)
asserter(5, [], remove_num, [0,0,0,0], 0)        
    </code>
</pre>